Week5/music_network/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root :to => "concerts#index"

resources :concerts do
	resources :comments
	end

end

Week5/music_network/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :concert

  validates :name, presence: true
  validates :comment, presence: true
end

Week5/music_network/app/models/concert.rb
class Concert < ApplicationRecord
	has_many :comments 

	validates :artist, presence: true
	validates :venue, presence: true
	validates :city, presence: true
	validates :date, presence: true
	validates :price, presence: true
	validates :description, presence: true
end

Week5/music_network/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@comments = Comment.find_by(concert_id: params[:id])
	end

	def create
		#create a new comment from params passed in form
		@concert = Concert.find(params[:concert_id])
		@new_comment = @concert.comments.new(new_comment_params)
		@new_comment.save
		redirect_to("/concerts/#{@concert.id}")
	end

	private

	def new_comment_params
		params.require(:comment).permit(:name, :comment)
	end
end

Week5/music_network/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

	def index
		@concerts_today = Concert.where(date: Time.now..Time.now.end_of_day)
		@concerts_month = Concert.where(date: Time.now.end_of_day..Time.now.end_of_month)
	end

	def show
		#display a single concert from an id
		@concert = Concert.find_by(id: params[:id])
		@comments = @concert.comments 
		@new_comment = @concert.comments.new
	end

	def new
		#display form page for new concert
		@new_concert = Concert.new
	end

	def create
		#create a new concert from params passed in form
		@new_concert = Concert.new(new_concert_params)
		
		if @new_concert.save
			redirect_to "/concerts/#{@new_concert.id}"
		else
			render 'new'
		end
	end

	def new_concert_params
		params.require(:concert).permit(:artist, :venue, :city, :date, :price, :description)
	end
end

Week5/music_network/app/helpers/comments_helper.rb
module CommentsHelper
end

Week5/music_network/app/helpers/concerts_helper.rb
module ConcertsHelper
end

Week5/music_network/app/views/concerts/index.html.erb
<h2> Concerts </h2>


<div>
<h3> Coming up today... </h3>

<% @concerts_today.each do |c| %>
	<%= link_to "#{c.artist}", concert_path(c) %> @ 
	<%= c.venue %>
	<br>
<% end %>
<br>
</div>
<hr>

<div>
<h3> Later on this month... </h3>

<% @concerts_month.each do |c| %>
<%= link_to "#{c.artist}", concert_path(c) %> @ 
	<%= c.venue %>
	<br>
<% end %>
<br>
</div>

<%= link_to "Add new concert", new_concert_path %>

Week5/music_network/app/views/concerts/new.html.erb
<h1> Add a New Concert </h1>

<%= form_for @new_concert do |f| %>
<%= f.label :artist %>
<%= f.text_field :artist, required: true, class: "box" %>
<br>
<%= f.label :venue %>
<%= f.text_field :venue, required: true, class: "box" %>
<br>
<%= f.label :city %>
<%= f.text_field :city, required: true, class: "box" %>
<br>
<%= f.label :date %>
<%= f.datetime_field :date, required: true, class: "box" %>
<br>
<%= f.label :price %>
<%= f.text_field :price, class: "box" %>
<br>
<%= f.label :description %>
<%= f.text_field :description, class: "box" %>
<br>
<%= f.button %>
<% end %>

Week5/music_network/app/views/concerts/show.html.erb
<h1> <%= @concert.artist %> </h1>

<h2> Details </h2>

<%= @concert.venue %>,
<%= @concert.city %>.
<br>
<%= @concert.date %>.
<br>
$<%= @concert.price %>.
<br>
<%= @concert.description %>


<h3> Comments </h3>

<% if @comments %>
	<% @comments.each do |x| %>
	<%= x.name %> -  
	<%= x.comment %>
	<br>
	<% end %>
<% end %>


<h3> Add comments </h3>

<%= form_for [@concert, @new_comment] do |f| %>
<%= f.label :name %>
<%= f.text_field :name, required: true, class: "box" %>
<br>
<%= f.label :comment %>
<%= f.text_field :comment, required: true, class: "box" %>
<br>
<%= f.submit %>
<% end %>