Week4/auction/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/', to: 'site#home'

  get '/users', to: 'users#index', as: :user

  get '/products', to: 'products#index', as: :product

  get '/products/new', to: 'products#new', as: :product_new

  post '/products', to: 'products#create'
end

Week4/auction/app/models/product.rb
class Product < ApplicationRecord

	belongs_to :user

	validates :title, presence: true

	validates :description, presence: true

	validates :deadline, presence: true

end

Week4/auction/app/models/user.rb
class User < ApplicationRecord

	has_many :products
	
	validates :name, presence: true

	validates :email, presence: true, uniqueness: true
end

Week4/auction/app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index

		# @user = User.all
		@products = Product.all
	end

	def new
		# @user = User.find_by(id: params[:id])
		@product = Product.new
	end

	def create 
		# user = User.find(params[:user_id])
		product = Product.new(
			title: params[:product][:title],
			description: params[:product][:description],
			deadline: params[:product][:deadline])
		product.save

		redirect_to("/products")
	end

	def destroy
	end
end

Week4/auction/app/controllers/site_controller.rb
class SiteController < ApplicationController

	def home
		render 'home'
	end
end

Week4/auction/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	# show users 
		@users = User.order(created_at: :desc)
	end

	def show
	#display a single user from an id
		@user = User.find_by(id: params[:id])

		unless @user
			render 'No user exists...'
		end
	end

	def new
	# display form page for creating new user
		@new_user = User.new
	end

	def create
	# create a new user from params in form
		new_user = User.new(
			name: params[:user][:name],
			email: params[:user][:email])
		new_user.save

		redirect_to "/users/#{new_user.id}"
	end

	def destroy
	end

end

Week4/auction/app/helpers/site_helper.rb
module SiteHelper
end

Week4/auction/app/views/layouts/_header.html.erb
<h1><img src="http://coolspotters.com/files/photos/26546/ruby-on-rails-profile.png" height="100px"> RailsBay </h1>

<%= link_to 'Users', user_path %>

<%= link_to 'Products', product_path %>

Week4/auction/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auction</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render("layouts/header") %>

    <%= yield %>
  </body>
</html>

Week4/auction/app/views/products/index.html.erb
<h1> Products </h1>

<h2> List a new product: </h2>

<%= link_to 'New Product', product_new_path %>

<h2> For sale: </h2>

<ul>
	<% @products.each do |item| %>
		<li>
			<%= item.title %> -
			<%= item.description %> --
			<%= item.deadline %> 
		</li>
	<% end %>
</ul>

Week4/auction/app/views/products/new.html.erb
<h1>Post some shit</h1>

<%= form_for @product do |x| %>
	<%= x.label :title %>
	<%= x.text_field :title %>
	<br>
	<%= x.label :description %>
	<%= x.text_field :description %>
	<br>
	<%= x.label :deadline %>
	<%= x.datetime_field :deadline %>
	<br>
	<%= x.submit "Post that shit" %>
<% end %>