Week4/timetracking/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "site#home"
  
  resources :projects do
    resources :time_entries
  end
end

Week4/timetracking/app/models/project.rb
class Project < ApplicationRecord
	has_many :time_entries

	validates :name, 
		presence: true,
		uniqueness: true,
		length: { maximum: 30 },
		format: { with: /\A[a-zA-Z\s]+\Z/}

	def self.clean_old
		where("created_at > ?", 7.days.ago).destroy_all
	end
end

Week4/timetracking/app/models/time_entry.rb
class TimeEntry < ApplicationRecord
	belongs_to :project

	validates :hours, presence: true, 
				numericality: { 
					only_integer: true, 
					greater_than_or_equal_to: 0 }
	validates :minutes, presence: true, 
  				numericality: {
  					only_integer: true,
  					greater_than_or_equal_to: 0 }
	validates :date, presence: true
end

Week4/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		#show projects in descending order, only last ten
		@projects = Project.order(created_at: :desc).limit(10)
	end

	def show
		#display a single project from an id
		@project = Project.find_by(id: params[:id])

		unless @project
			render "no_projects_found"
		end
	end

	def new
		#display form page for new project
		@new_project = Project.new
	end

	def create
		#create a new project from params passed in form
		@new_project = Project.new(
			name: params[:project][:name],
			description: params[:project][:description]
			)
		
		if @new_project.save
			redirect_to "/projects/#{new_project.id}"
		else
			render 'new'
		end
	end
end

Week4/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
	
	def home
		render 'home'
	end

	def contact
		render 'contact'
	end

	def say_name
		@name = params[:name]

		render 'say_name'
	end
end

Week4/timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController

	def index
	# Input 
	# - project id under params[:id]
	# Output
	# - all entries for the project
	
	@project = Project.find(params[:project_id])
	@time_entries = @project.time_entries
	end

	def new
	# Input
	# - params[:project_id]
	# Output
	# 1. Find the Project
	# 2. Instantiate new time entry for the project
	@project = Project.find(params[:project_id])
	@time_entry = @project.time_entries.new
	end

	def create
	# Input
	# - params[:project_id]
	# - params[:time_entry]
	# 1. Find the project
	# 2. Instantiate the new time entry with time_entry params
	# 3. save the time entry
	# 4. redirect back to project's time entries
	project = Project.find(params[:project_id])
	time_entry = project.time_entries.new(time_entry_params)
		if time_entry.save
			flash[:notice] = "Project created successfully"
			redirect_to("/projects/#{project.id}/time_entries")
		else
			render 'new'
		end
	end

	def edit
	# Input
	# - params[:project_id]
	# - params[:id]
	# Output
	# - the edit form
	@project = Project.find(params[:project_id])
	@time_entry = @project.time_entries.find(params[:id])
	end

	def update
		project = Project.find(params[:project_id])
		time_entry = project.time_entries.find(params[:id])
		time_entry.update(time_entry_params)

		redirect_to "/projects/#{project.id}/time_entries"
	end



	private

	def time_entry_params
		params.require(:time_entry).permit(:hours, :minutes, :date)
	end
end

Week4/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

Week4/timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

Week4/timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<%= render("other_stuff/header") %>

    <%= yield %>

    <hr>

    <footer>
    	<p>Made with love at Ironhack</p>
    </footer>
  </body>
</html>

Week4/timetracking/app/views/site/contact.html.erb
<h1>Contact us</h1>

<h2>...because we care!</h2>

<h3><a href="#">contact@example.com</a></h3>

Week4/timetracking/app/views/site/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
</head>
<body>

<h1>Home</h1>

<h2>Track time</h2>

<%= link_to 'Projects', projects_path %>

</body>
</html>

Week4/timetracking/app/views/site/say_name.html.erb
<h1>
	Hello <%= @name %> !
</h1>